### ISSUE TITLE
error compiling - IRDaikinServer.h

### ISSUE THREAD

**Issue by sommo** [Andreaqc/IR-Daikin-Server-ESP8266#2]
Hi,
i'm getting this error while compiling via Arduino:

...\Documents\Arduino\libraries\IRDaikinServer/IRDaikinServer.h:60:84: error: expected declaration before '%>' token

   <meta class="js-ga-set" name="userId" content="4d32417c570123659cb2ef91dffa1577" %>

                                                                                    ^

exit status 1

i just copy your IRDaikinServer.h into arduino's library folder, it find it without problem but get this error while compiling, you know why?
i have all libraries updated.
Thank you,

**Comment by andreacucci** [comment]
Hi @sommo 
did you try putting them inside your project folder?
How did you copy this repo? Did you clone it?

**Comment by sommo** [comment]
Hi @Andreaqc ,
i tried to compile (IRDaikinServer.ino) it through arduino ide and adding first your IRDaikinServer.h (downloaded) into arduino library folder.
Or i need to use another compiler like platform.io (atom) ?
Forse possiamo anche parlare in italiano :)

**Comment by andreacucci** [comment]
Did you try putting IRDaikinServer.h in the same folder as IRDaikinServer.ino?
That *.h contains just a pair of useful definitions that i then use inside the *.ino, nothing like a library.

Let's stick to english so more people can understand what we say. :)

**Comment by sommo** [comment]
ok for english @Andreaqc,
anyway doesn't matter where i put the IRDaikinServer.h and what compiler i use, i always recieve this error:

src\IRDaikinServer.h:54:84: error: expected declaration before '%>' token
<meta class="js-ga-set" name="userId" content="4d32417c570123659cb2ef91dffa1577" %>
^

this time with platformio.

**Comment by andreacucci** [comment]
Could you copy the content of IRDaikinServer.h and put it in place of its include statement (#include "IRDaikinServer.h") inside IRDaikinServer.ino and try to compile?

**Comment by sommo** [comment]
same problem, and is here:

<meta class="js-ga-set" name="userId" content="4d32417c570123659cb2ef91dffa1577" %>

somehow can't compile.

How you compile your skecth? via arduino ide?

**Comment by sommo** [comment]
my mistake, i don't know why but IRDaikinServer.h was a different file then yours, so i copied the right one and it compile without problem, now i test it.

a question remains, how you get current temperature if none sensor (like dht22), is configured through arduino/wemos?

**Comment by andreacucci** [comment]
I'm glad you got it sorted out.
However this code doesn't read any temperature.
